### PR TITLE
fix internet radio search on IOS app

### LINKED ISSUE #856: Internet Radio search is broken on iOS app
iOS: 17.5.1

### PR DESCRIPTION
**Pull request by klay2000**
### What does this change intend to accomplish?
fixes internet radio search on ios

### Checklist

* [x] Have you tested your changes and ensured they work?
* [x] If applicable, have you updated the CHANGELOG?

closes #856

### CODE REVIEW

**Review by rtertiaer — APPROVED** [review]
I don't love it but it is what it is. For whomever finds this PR later, the first server is pinned because of upstream's SSL cert configuration - there are no subject alternative names that specify `all.api.radio-browser.info`. I'm less concerned about this than would first appear, because we're still load balancing the expensive requests across the servers listed in this request.

File: web/src/pages/Settings/Streams/StreamModal/StreamModal.jsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ const InternetRadioSearch = ({ onChange }) => {
 
     return (
         React.useEffect(() => {
-            fetch("http://all.api.radio-browser.info/json/servers").then((res) =>
+            fetch("https://at1.api.radio-browser.info/json/servers").then((res) =>
```
Comment (linknum23) [inline web/src/pages/Settings/Streams/StreamModal/StreamModal.jsx:133]: There should be a comment here

Comment (linknum23) [reply web/src/pages/Settings/Streams/StreamModal/StreamModal.jsx:135]: what happens when at1 is down?
